(function (root) {
'use strict';

const PAGE = { w: 595, h: 842, margin: 48 };
const CONTENT = { x: PAGE.margin, w: PAGE.w - 2 * PAGE.margin };
const MAX_Y = PAGE.h - PAGE.margin - 28;

const COLORS = {
    text:        [15, 20, 28],
    textMuted:   [95, 105, 120],
    textSubtle:  [155, 165, 180],
    border:      [222, 226, 232],
    accent:      [4, 120, 87],
    high:        [190, 18, 60],
    warning:     [180, 83, 9],
    info:        [14, 124, 177],
    secure:      [4, 120, 87],
    cardBg:      [245, 247, 250],
    bgAlt:       [238, 241, 246],
};

function rgb(c) { return c; }

function toJsPDF() {
    const jspdfNs = root.jspdf || window.jspdf;
    if (!jspdfNs || !jspdfNs.jsPDF) throw new Error('jsPDF library not loaded');
    return new jspdfNs.jsPDF({ unit: 'pt', format: 'a4', compress: true });
}

class PDF {
    constructor() {
        this.doc = toJsPDF();
        this.y = PAGE.margin;
        this.pageNo = 1;
        this.totalPages = 0;
        this.results = null;
        this.pageHeaders = [];
        this.titleStartY = null;
    }

    setFont(family, style, size) {
        this.doc.setFont(family || 'helvetica', style || 'normal');
        if (size) this.doc.setFontSize(size);
    }

    color(rgbArr) {
        this.doc.setTextColor(rgbArr[0], rgbArr[1], rgbArr[2]);
        this.doc.setDrawColor(rgbArr[0], rgbArr[1], rgbArr[2]);
        this.doc.setFillColor(rgbArr[0], rgbArr[1], rgbArr[2]);
    }

    ensure(spaceNeeded) {
        if (this.y + spaceNeeded > MAX_Y) {
            this.addPage();
        }
    }

    addPage(skipHeader) {
        this.doc.addPage();
        this.pageNo++;
        this.y = PAGE.margin;
        if (!skipHeader) this.drawPageHeader();
    }

    drawPageHeader() {
        const d = this.doc;
        d.setFont('helvetica', 'normal'); d.setFontSize(8);
        d.setTextColor(...COLORS.textSubtle);
        d.text('IPA Auditor - ' + (this.results?.appInfo?.appName || 'Report'), PAGE.margin, 28);
        d.text(String(this.pageNo), PAGE.w - PAGE.margin, 28, { align: 'right' });
        d.setDrawColor(...COLORS.border);
        d.setLineWidth(0.5);
        d.line(PAGE.margin, 34, PAGE.w - PAGE.margin, 34);
        this.y = PAGE.margin + 8;
    }

    drawFooter() {
        const d = this.doc;
        const tp = d.internal.getNumberOfPages();
        for (let i = 1; i <= tp; i++) {
            d.setPage(i);
            d.setFont('helvetica', 'normal'); d.setFontSize(7);
            d.setTextColor(...COLORS.textSubtle);
            d.text('Generated by IPA Auditor / ' + new Date().toISOString(), PAGE.margin, PAGE.h - 24);
            d.text('Page ' + i + ' of ' + tp, PAGE.w - PAGE.margin, PAGE.h - 24, { align: 'right' });
        }
    }

    text(str, opts) {
        const o = opts || {};
        const size = o.size || 10;
        const style = o.style || 'normal';
        const color = o.color || COLORS.text;
        const lineHeight = o.lineHeight || (size * 1.4);
        const x = o.x ?? CONTENT.x;
        const maxW = o.maxW ?? CONTENT.w;
        this.setFont('helvetica', style, size);
        this.doc.setTextColor(...color);
        const text = String(str ?? '');
        const lines = this.doc.splitTextToSize(text, maxW);
        const totalH = lines.length * lineHeight;
        this.ensure(totalH + 4);
        this.doc.text(lines, x, this.y);
        this.y += totalH;
        if (o.gap) this.y += o.gap;
        return this;
    }

    pageTitle(title, subtitle) {
        this.ensure(64);
        this.setFont('helvetica', 'bold', 22);
        this.color(COLORS.text);
        this.doc.text(title, CONTENT.x, this.y);
        this.y += 24;
        if (subtitle) {
            this.setFont('helvetica', 'normal', 11);
            this.color(COLORS.textMuted);
            const lines = this.doc.splitTextToSize(subtitle, CONTENT.w);
            this.doc.text(lines, CONTENT.x, this.y);
            this.y += lines.length * 14;
        }
        this.y += 16;
    }

    sectionHeader(title, accent) {
        this.ensure(36);
        this.y += 8;
        const d = this.doc;
        d.setFillColor(...(accent || COLORS.accent));
        d.rect(CONTENT.x, this.y - 8, 3, 18, 'F');
        d.setFont('helvetica', 'bold'); d.setFontSize(14);
        d.setTextColor(...COLORS.text);
        d.text(title, CONTENT.x + 10, this.y + 6);
        this.y += 22;
        d.setDrawColor(...COLORS.border);
        d.setLineWidth(0.5);
        d.line(CONTENT.x, this.y, CONTENT.x + CONTENT.w, this.y);
        this.y += 12;
    }

    subHeader(title) {
        this.ensure(20);
        this.y += 6;
        this.setFont('helvetica', 'bold', 10.5);
        this.color(COLORS.text);
        this.doc.text(title, CONTENT.x, this.y);
        this.y += 14;
    }

    keyValueGrid(items, opts) {
        const o = opts || {};
        const cols = o.cols || 2;
        const gap = 12;
        const colW = (CONTENT.w - gap * (cols - 1)) / cols;
        const rowH = 32;
        const visible = items.filter(([, v]) => v != null && v !== '');
        for (let i = 0; i < visible.length; i += cols) {
            this.ensure(rowH + 4);
            for (let c = 0; c < cols; c++) {
                const item = visible[i + c];
                if (!item) continue;
                const x = CONTENT.x + c * (colW + gap);
                const [k, v] = item;
                const d = this.doc;
                d.setFillColor(...COLORS.cardBg);
                d.roundedRect(x, this.y, colW, rowH - 4, 4, 4, 'F');
                d.setFont('helvetica', 'normal'); d.setFontSize(7.5);
                d.setTextColor(...COLORS.textSubtle);
                d.text(String(k).toUpperCase(), x + 8, this.y + 11);
                d.setFont('helvetica', 'normal'); d.setFontSize(10);
                d.setTextColor(...COLORS.text);
                const valLines = d.splitTextToSize(String(v), colW - 16);
                d.text(valLines[0] || '', x + 8, this.y + 23);
            }
            this.y += rowH;
        }
    }

    coverPage() {
        const r = this.results;
        const d = this.doc;
        const cx = PAGE.w / 2;

        d.setFillColor(...COLORS.bgAlt);
        d.rect(0, 0, PAGE.w, PAGE.h, 'F');

        d.setFont('helvetica', 'bold'); d.setFontSize(11);
        d.setTextColor(...COLORS.textMuted);
        d.text('IPA AUDITOR  /  iOS STATIC SECURITY REPORT', cx, 140, { align: 'center' });

        d.setFont('helvetica', 'bold'); d.setFontSize(34);
        d.setTextColor(...COLORS.text);
        const name = r.appInfo?.appName || 'iOS Application';
        d.text(name, cx, 200, { align: 'center' });

        d.setFont('helvetica', 'normal'); d.setFontSize(12);
        d.setTextColor(...COLORS.textMuted);
        d.text(r.appInfo?.bundleId || '', cx, 222, { align: 'center' });
        d.text('v' + (r.appInfo?.version || '?') + ' (' + (r.appInfo?.build || '?') + ')  /  ' + (r.appInfo?.fileSize || ''), cx, 240, { align: 'center' });

        const score = r.securityScore ?? 0;
        const scoreColor = score >= 85 ? COLORS.secure : score >= 70 ? COLORS.info : score >= 50 ? COLORS.warning : COLORS.high;
        const scoreLabel = score >= 85 ? 'Excellent' : score >= 70 ? 'Good' : score >= 50 ? 'Fair' : score >= 30 ? 'Poor' : 'Critical';

        d.setDrawColor(...scoreColor);
        d.setLineWidth(8);
        d.circle(cx, 350, 65);
        d.setFont('helvetica', 'bold'); d.setFontSize(46);
        d.setTextColor(...scoreColor);
        d.text(String(score), cx, 362, { align: 'center' });
        d.setFont('helvetica', 'normal'); d.setFontSize(10);
        d.setTextColor(...COLORS.textMuted);
        d.text('/ 100', cx, 378, { align: 'center' });
        d.setFont('helvetica', 'bold'); d.setFontSize(13);
        d.setTextColor(...scoreColor);
        d.text(scoreLabel.toUpperCase(), cx, 440, { align: 'center' });

        const sum = r.summary || {};
        const stats = [
            { label: 'HIGH',    val: sum.high || 0,    color: COLORS.high },
            { label: 'WARNING', val: sum.warning || 0, color: COLORS.warning },
            { label: 'INFO',    val: sum.info || 0,    color: COLORS.info },
            { label: 'SECURE',  val: sum.secure || 0,  color: COLORS.secure },
        ];
        const sw = 100;
        const sgap = 12;
        const totalW = sw * 4 + sgap * 3;
        const sx0 = cx - totalW / 2;
        const sy = 480;
        stats.forEach((s, i) => {
            const x = sx0 + i * (sw + sgap);
            d.setFillColor(255, 255, 255);
            d.setDrawColor(...COLORS.border);
            d.setLineWidth(0.5);
            d.roundedRect(x, sy, sw, 56, 6, 6, 'FD');
            d.setFont('helvetica', 'bold'); d.setFontSize(22);
            d.setTextColor(...s.color);
            d.text(String(s.val), x + sw / 2, sy + 30, { align: 'center' });
            d.setFont('helvetica', 'normal'); d.setFontSize(8);
            d.setTextColor(...COLORS.textMuted);
            d.text(s.label, x + sw / 2, sy + 46, { align: 'center' });
        });

        const meta = [
            ['Bundle ID',  r.appInfo?.bundleId],
            ['Version',    r.appInfo?.version + ' (' + r.appInfo?.build + ')'],
            ['Min iOS',    r.appInfo?.minOS],
            ['Executable', r.appInfo?.executableName],
            ['Bin Type',   r.binType],
            ['File size',  r.appInfo?.fileSize],
            ['Scanned at', new Date().toISOString()],
        ];
        let my = 580;
        d.setFontSize(9);
        for (const [k, v] of meta) {
            if (!v) continue;
            d.setFont('helvetica', 'normal'); d.setTextColor(...COLORS.textMuted);
            d.text(k, PAGE.margin + 40, my);
            d.setFont('helvetica', 'normal'); d.setTextColor(...COLORS.text);
            d.text(String(v), PAGE.margin + 130, my);
            my += 16;
        }

        if (r.appInfo?.sha256) {
            d.setFont('helvetica', 'normal'); d.setFontSize(7);
            d.setTextColor(...COLORS.textSubtle);
            d.text('SHA-256: ' + r.appInfo.sha256, cx, PAGE.h - 60, { align: 'center', maxWidth: 480 });
        }

        d.setFont('helvetica', 'italic'); d.setFontSize(8);
        d.setTextColor(...COLORS.textSubtle);
        d.text('Automated static analysis. Pattern matching + Mach-O / plist / CMS parsing. OWASP MASVS aligned.',
               cx, PAGE.h - 40, { align: 'center', maxWidth: 480 });
        d.text('Findings are indicative. Manual triage by a qualified security professional is required.',
               cx, PAGE.h - 28, { align: 'center', maxWidth: 480 });
    }

    summaryPage() {
        this.addPage();
        const r = this.results;
        this.pageTitle('Executive Summary', 'High-level overview of static analysis findings.');

        this.sectionHeader('Application');
        this.keyValueGrid([
            ['Name',        r.appInfo?.appName],
            ['Bundle ID',   r.appInfo?.bundleId],
            ['Version',     r.appInfo?.version + ' (' + r.appInfo?.build + ')'],
            ['Min iOS',     r.appInfo?.minOS],
            ['Binary',      r.appInfo?.executableName],
            ['Bin Type',    r.binType],
            ['File size',   r.appInfo?.fileSize],
            ['File count',  String((r.files || []).length)],
        ]);

        this.sectionHeader('Score Breakdown');
        const sum = r.summary || {};
        this.barRow('High',    sum.high || 0,    COLORS.high);
        this.barRow('Warning', sum.warning || 0, COLORS.warning);
        this.barRow('Info',    sum.info || 0,    COLORS.info);
        this.barRow('Secure',  sum.secure || 0,  COLORS.secure);

        if (r.machoSummary) {
            this.sectionHeader('Binary Hardening');
            const cs = r.machoSummary.checksec || (r.machoSummary.slices?.[0]?.checksec) || {};
            const checks = [
                ['PIE / ASLR',         cs.pie],
                ['Stack Canary',       cs.stackCanary],
                ['ARC',                cs.arc],
                ['Code Signed',        cs.codeSigned],
                ['NX Heap',            cs.nx_heap],
                ['NX Stack',           cs.nx_stack],
                ['Two-Level NS',       cs.twoLevelNamespace],
                ['FairPlay Encrypted', cs.encryptedFairPlay],
            ];
            this.checkGrid(checks);
        }

        if (r.trackers && r.trackers.length) {
            this.sectionHeader('Trackers & SDKs Detected');
            this.text(r.trackers.map(t => t.name).join(', '), { color: COLORS.text, size: 9 });
        }
    }

    barRow(label, count, color) {
        this.ensure(22);
        const d = this.doc;
        const barX = CONTENT.x + 110;
        const barW = CONTENT.w - 110 - 50;
        const maxCount = 50;
        const fill = Math.min(1, count / maxCount);

        d.setFont('helvetica', 'normal'); d.setFontSize(10);
        d.setTextColor(...COLORS.text);
        d.text(label, CONTENT.x, this.y + 9);

        d.setFillColor(...COLORS.cardBg);
        d.roundedRect(barX, this.y, barW, 12, 3, 3, 'F');
        if (fill > 0) {
            d.setFillColor(...color);
            d.roundedRect(barX, this.y, Math.max(4, barW * fill), 12, 3, 3, 'F');
        }
        d.setFont('helvetica', 'bold'); d.setFontSize(10);
        d.setTextColor(...color);
        d.text(String(count), CONTENT.x + CONTENT.w - 4, this.y + 9, { align: 'right' });
        this.y += 18;
    }

    checkGrid(checks) {
        const cols = 2;
        const gap = 10;
        const colW = (CONTENT.w - gap) / cols;
        const rowH = 26;
        for (let i = 0; i < checks.length; i += cols) {
            this.ensure(rowH + 2);
            for (let c = 0; c < cols; c++) {
                const item = checks[i + c];
                if (!item) continue;
                const [name, ok] = item;
                const x = CONTENT.x + c * (colW + gap);
                const color = ok ? COLORS.secure : COLORS.high;
                const d = this.doc;
                d.setFillColor(...COLORS.cardBg);
                d.roundedRect(x, this.y, colW, rowH - 4, 4, 4, 'F');
                d.setDrawColor(...color);
                d.setLineWidth(2);
                d.line(x, this.y + 2, x, this.y + rowH - 6);
                d.setFont('helvetica', 'bold'); d.setFontSize(10);
                d.setTextColor(...color);
                d.text(ok ? '✓' : '✗', x + 10, this.y + 15);
                d.setFont('helvetica', 'normal'); d.setFontSize(9.5);
                d.setTextColor(...COLORS.text);
                d.text(name, x + 24, this.y + 15);
            }
            this.y += rowH;
        }
    }

    findingsSection() {
        const r = this.results;
        this.addPage();
        this.pageTitle('Findings', 'Every detected rule with all instances. Severities: High, Warning, Info, Secure.');

        const sections = [
            { key: 'high',    color: COLORS.high,    title: 'High Severity' },
            { key: 'warning', color: COLORS.warning, title: 'Warning' },
            { key: 'info',    color: COLORS.info,    title: 'Informational' },
            { key: 'secure',  color: COLORS.secure,  title: 'Secure Controls Detected' },
        ];
        for (const sec of sections) {
            const groups = r.groupedFindings?.[sec.key] || [];
            if (!groups.length) continue;
            this.sectionHeader(sec.title + '  (' + groups.length + ')', sec.color);
            for (const g of groups) this.findingCard(g, sec.color);
        }
        if (!sections.some(s => (r.groupedFindings?.[s.key] || []).length)) {
            this.text('No findings.', { color: COLORS.textMuted });
        }
    }

    findingCard(group, color) {
        const d = this.doc;
        this.ensure(50);

        d.setFillColor(...COLORS.cardBg);
        const cardX = CONTENT.x;
        const cardW = CONTENT.w;
        const headerH = 30;
        d.roundedRect(cardX, this.y, cardW, headerH, 4, 4, 'F');
        d.setFillColor(...color);
        d.rect(cardX, this.y, 3, headerH, 'F');

        const sevW = 60;
        const sevPad = 6;
        d.setFillColor(...color);
        d.roundedRect(cardX + 10, this.y + 7, sevW, 16, 8, 8, 'F');
        d.setFont('helvetica', 'bold'); d.setFontSize(7);
        d.setTextColor(255, 255, 255);
        d.text(group.severity.toUpperCase(), cardX + 10 + sevW / 2, this.y + 17, { align: 'center' });

        d.setFont('helvetica', 'bold'); d.setFontSize(11);
        d.setTextColor(...COLORS.text);
        const titleX = cardX + 10 + sevW + sevPad;
        const titleMaxW = cardW - (titleX - cardX) - 110;
        const titleLines = d.splitTextToSize(group.ruleName, titleMaxW);
        d.text(titleLines[0] || group.ruleName, titleX, this.y + 19);

        d.setFont('helvetica', 'normal'); d.setFontSize(8.5);
        d.setTextColor(...COLORS.textMuted);
        const confText = (group.avgConfidence ?? 50) + '%  /  ' + group.instances.length + ' ' + (group.instances.length === 1 ? 'instance' : 'instances');
        d.text(confText, cardX + cardW - 8, this.y + 19, { align: 'right' });

        this.y += headerH + 6;

        if (group.description) {
            this.text(group.description, { size: 9, color: COLORS.textMuted, gap: 4 });
        }

        const meta = [];
        if (group.cwe)   meta.push('CWE: ' + group.cwe);
        if (group.owasp) meta.push('OWASP: ' + group.owasp);
        if (group.masvs) meta.push('MASVS: ' + group.masvs);
        if (group.category) meta.push(group.category);
        if (meta.length) {
            this.text(meta.join('   /   '), { size: 8, color: COLORS.accent, style: 'normal', gap: 4 });
        }

        this.subHeader('Instances (' + group.instances.length + ')');
        let printed = 0;
        for (let i = 0; i < group.instances.length; i++) {
            const inst = group.instances[i];
            this.instanceRow(i + 1, inst, color);
            printed++;
        }
        this.y += 8;
    }

    instanceRow(num, inst, color) {
        const d = this.doc;
        this.ensure(34);
        const x = CONTENT.x;
        const w = CONTENT.w;

        d.setFillColor(252, 252, 253);
        d.roundedRect(x, this.y, w, 28, 3, 3, 'F');
        d.setDrawColor(...COLORS.border);
        d.setLineWidth(0.4);
        d.roundedRect(x, this.y, w, 28, 3, 3, 'S');

        d.setFont('helvetica', 'bold'); d.setFontSize(7);
        d.setFillColor(...color);
        d.roundedRect(x + 8, this.y + 8, 18, 12, 6, 6, 'F');
        d.setTextColor(255, 255, 255);
        d.text('#' + num, x + 8 + 9, this.y + 16, { align: 'center' });

        const fileX = x + 32;
        const isBin = inst.file && inst.file.startsWith('BINARY:');
        const fileLabel = (isBin ? inst.file.replace('BINARY:', '') + ' (binary)' : (inst.file || '')) + (inst.line ? ':' + inst.line : '');
        d.setFont('courier', 'normal'); d.setFontSize(8.5);
        d.setTextColor(60, 90, 175);
        const flLines = d.splitTextToSize(fileLabel, w - 40 - 130);
        d.text(flLines[0] || '', fileX, this.y + 13);

        if (inst.binaryOffset) {
            d.setFont('helvetica', 'bold'); d.setFontSize(7);
            d.setTextColor(...COLORS.warning);
            d.text('@ ' + inst.binaryOffset, x + w - 8, this.y + 13, { align: 'right' });
        }
        if (inst.confidence != null) {
            d.setFont('helvetica', 'bold'); d.setFontSize(7);
            d.setTextColor(...COLORS.textMuted);
            d.text(inst.confidence + '%' + (inst.entropy != null ? '  H=' + inst.entropy : ''), x + w - 8, this.y + 23, { align: 'right' });
        }

        d.setFont('courier', 'normal'); d.setFontSize(8);
        d.setTextColor(...COLORS.text);
        const matchLines = d.splitTextToSize(inst.match || '', w - 40 - 140);
        d.text(matchLines[0] || '', fileX, this.y + 23);

        this.y += 32;

        if (inst.snippet) {
            const snipLines = inst.snippet.split('\n').slice(0, 6);
            d.setFont('courier', 'normal'); d.setFontSize(7.5);
            d.setTextColor(...COLORS.textMuted);
            const totalH = snipLines.length * 10 + 8;
            this.ensure(totalH);
            d.setFillColor(248, 248, 250);
            d.roundedRect(x, this.y, w, totalH, 3, 3, 'F');
            for (let i = 0; i < snipLines.length; i++) {
                const line = snipLines[i].length > 110 ? snipLines[i].slice(0, 110) + '…' : snipLines[i];
                if (line.trim().startsWith('>>>')) {
                    d.setTextColor(...COLORS.warning);
                } else {
                    d.setTextColor(...COLORS.textMuted);
                }
                d.text(line, x + 6, this.y + 10 + i * 10);
            }
            this.y += totalH + 4;
        } else {
            this.y += 2;
        }
    }

    binaryPage() {
        const r = this.results;
        if (!r.machoSummary) return;
        this.addPage();
        this.pageTitle('Binary Analysis', 'Mach-O structure, hardening, and linked libraries.');

        const slices = r.machoSummary.type === 'fat' ? (r.machoSummary.slices || []) : [r.machoSummary];
        for (const s of slices) {
            this.sectionHeader('Slice: ' + (s.arch || '?'));
            this.keyValueGrid([
                ['Architecture', s.arch],
                ['Bits',         s.bits ? s.bits + '-bit' : null],
                ['Platform',     s.platform],
                ['Min OS',       s.minOS],
                ['SDK',          s.sdk],
                ['UUID',         s.uuid],
                ['Source Ver',   s.sourceVersion],
                ['Filetype',     s.filetype],
            ]);

            this.subHeader('Hardening');
            const cs = s.checksec || {};
            this.checkGrid([
                ['PIE / ASLR',         cs.pie],
                ['Stack Canary',       cs.stackCanary],
                ['ARC',                cs.arc],
                ['Code Signed',        cs.codeSigned],
                ['NX Heap',            cs.nx_heap],
                ['NX Stack',           cs.nx_stack],
                ['Two-Level NS',       cs.twoLevelNamespace],
                ['FairPlay Encrypted', cs.encryptedFairPlay],
            ]);

            if (s.segments && s.segments.length) {
                this.subHeader('Segments (' + s.segments.length + ')');
                this.simpleTable(['Name', 'VM Addr', 'VM Size', 'Sections'],
                    s.segments.map(seg => [seg.name, seg.vmaddr, fmtSize(seg.vmsize), String(seg.sections.length)]),
                    [120, 130, 80, 60]);
            }
            if (s.dylibs && s.dylibs.length) {
                this.subHeader('Linked Libraries (' + s.dylibs.length + ')');
                const lines = s.dylibs.map(d => typeof d === 'string' ? d : d.name);
                this.bulletList(lines);
            }
            if (s.rpaths && s.rpaths.length) {
                this.subHeader('RPATHs (' + s.rpaths.length + ')');
                this.bulletList(s.rpaths);
            }
            if (s.codeSignature && s.codeSignature.codeDirectory) {
                this.subHeader('Code Directory');
                const cd = s.codeSignature.codeDirectory;
                this.keyValueGrid([
                    ['Identifier',  cd.identifier],
                    ['Team ID',     cd.teamId || '(none)'],
                    ['Hash',        cd.hashAlgorithm],
                    ['Page Size',   fmtSize(cd.pageSize || 4096)],
                    ['Code Slots',  String(cd.nCodeSlots)],
                    ['Spec Slots',  String(cd.nSpecialSlots)],
                    ['Flags',       (cd.flagNames || []).join(', ') || '(none)'],
                ]);
            }
        }
    }

    entitlementsPage() {
        const r = this.results;
        if (!r.provisioning && !r.entitlementsXml) return;
        this.addPage();
        this.pageTitle('Entitlements & Provisioning', 'Code-signing identity and runtime capabilities.');

        if (r.provisioning?.meta) {
            const m = r.provisioning.meta;
            this.sectionHeader('Provisioning Profile');
            this.keyValueGrid([
                ['Name',           m.name],
                ['Distribution',   m.distribution],
                ['App ID',         m.applicationIdentifier],
                ['Team',           m.teamName],
                ['Team ID',        (m.teamIdentifier || []).join(', ')],
                ['UUID',           m.uuid],
                ['Created',        m.creationDate],
                ['Expires',        m.expirationDate + (m.expired ? ' (EXPIRED)' : (m.daysUntilExpiry != null ? ' (' + m.daysUntilExpiry + 'd left)' : '')) ],
                ['Devices',        m.deviceCount + (m.provisionsAllDevices ? ' (all)' : '')],
                ['APS',            m.apsEnvironment || '(none)'],
                ['get-task-allow', m.getTaskAllow ? 'YES (debug)' : 'no'],
            ]);

            const certs = r.provisioning.certificates || [];
            if (certs.length) {
                this.subHeader('Developer Certificates (' + certs.length + ')');
                for (const c of certs) {
                    this.ensure(36);
                    const d = this.doc;
                    d.setFillColor(...COLORS.cardBg);
                    d.roundedRect(CONTENT.x, this.y, CONTENT.w, 32, 4, 4, 'F');
                    d.setFont('helvetica', 'bold'); d.setFontSize(9.5);
                    d.setTextColor(...COLORS.text);
                    d.text(c.subjectCN || '(unknown)', CONTENT.x + 8, this.y + 13);
                    d.setFont('helvetica', 'normal'); d.setFontSize(8);
                    d.setTextColor(...COLORS.textMuted);
                    const meta = [];
                    if (c.issuerCN) meta.push('Issuer: ' + c.issuerCN);
                    if (c.validity?.notAfter) meta.push('Until ' + c.validity.notAfter);
                    d.text(meta.join('   /   '), CONTENT.x + 8, this.y + 25);
                    this.y += 36;
                }
            }
        }

        const entObj = r.provisioning?.entitlements || tryParseXMLPlist(r.entitlementsXml);
        if (entObj && Object.keys(entObj).length) {
            this.sectionHeader('Entitlements (' + Object.keys(entObj).length + ')');
            const rows = Object.keys(entObj).sort().map(k => {
                const v = entObj[k];
                let display;
                if (Array.isArray(v)) display = v.join(', ');
                else if (typeof v === 'boolean') display = v ? 'YES' : 'NO';
                else if (typeof v === 'object' && v != null) display = JSON.stringify(v);
                else display = String(v);
                return [k, display];
            });
            this.simpleTable(['Key', 'Value'], rows, [220, CONTENT.w - 220]);
        }
    }

    atsPage() {
        const r = this.results;
        if (!r.ats) return;
        this.addPage();
        this.pageTitle('App Transport Security', 'NSAppTransportSecurity configuration analysis.');

        const a = r.ats;
        this.sectionHeader('Verdict');
        const verdictLabel = {
            'default-strict': 'Default (strict)',
            'strict': 'Strict - no exceptions',
            'strict-with-exceptions': 'Strict with explicit exceptions',
            'mixed': 'Mixed - some exceptions are risky',
            'mostly-disabled': 'Mostly disabled (per-domain re-enabled)',
            'globally-disabled': 'Globally disabled',
        }[a.verdict] || a.verdict;
        const vc = (a.verdict === 'strict' || a.verdict === 'default-strict' || a.verdict === 'strict-with-exceptions') ? COLORS.secure
                 : (a.verdict === 'mixed') ? COLORS.warning : COLORS.high;
        this.text(verdictLabel, { color: vc, style: 'bold', size: 12, gap: 6 });

        this.keyValueGrid([
            ['Arbitrary Loads',           a.allowsArbitraryLoads ? 'YES' : 'no'],
            ['Loads in WebView',          a.allowsArbitraryLoadsInWebContent ? 'YES' : 'no'],
            ['Loads for Media',           a.allowsArbitraryLoadsForMedia ? 'YES' : 'no'],
            ['Local Networking',          a.allowsLocalNetworking ? 'YES' : 'no'],
        ]);

        if (a.domains && a.domains.length) {
            this.sectionHeader('Exception Domains (' + a.domains.length + ')');
            this.simpleTable(['Domain', 'Sub', 'HTTP', 'Min TLS', 'PFS', 'Pinning', 'Issues'],
                a.domains.map(d => [
                    d.domain,
                    d.includesSubdomains ? '✓' : '',
                    d.allowsInsecureHTTPLoads ? 'allowed' : '-',
                    d.minimumTLSVersion,
                    d.requiresForwardSecrecy ? '✓' : 'no',
                    d.pinnedLeafIdentities ? 'leaf' : d.pinnedCAIdentities ? 'CA' : '-',
                    (d.issues || []).join(', '),
                ]),
                [120, 24, 50, 56, 26, 50, CONTENT.w - 350]);
        }
    }

    trackersPage() {
        const r = this.results;
        if (!r.trackers || !r.trackers.length) return;
        this.addPage();
        this.pageTitle('Trackers & SDKs', 'Third-party libraries detected in file list and binary strings.');

        const byCat = {};
        for (const t of r.trackers) (byCat[t.category || 'other'] ||= []).push(t.name);
        for (const [cat, names] of Object.entries(byCat)) {
            this.sectionHeader(cat.charAt(0).toUpperCase() + cat.slice(1) + '  (' + names.length + ')');
            this.bulletList(names);
        }
    }

    simpleTable(headers, rows, colWidths) {
        const d = this.doc;
        const rowH = 18;
        const startX = CONTENT.x;
        const totalW = colWidths.reduce((s, w) => s + w, 0);
        const scale = totalW > CONTENT.w ? CONTENT.w / totalW : 1;
        const widths = colWidths.map(w => w * scale);

        this.ensure(rowH * 2 + 4);

        d.setFillColor(...COLORS.cardBg);
        d.rect(startX, this.y, CONTENT.w, rowH, 'F');
        d.setFont('helvetica', 'bold'); d.setFontSize(8);
        d.setTextColor(...COLORS.textMuted);
        let cx = startX;
        for (let i = 0; i < headers.length; i++) {
            d.text(headers[i].toUpperCase(), cx + 4, this.y + 12);
            cx += widths[i];
        }
        this.y += rowH;
        d.setDrawColor(...COLORS.border);
        d.setLineWidth(0.3);

        for (const row of rows) {
            this.ensure(rowH + 2);
            d.setFont('helvetica', 'normal'); d.setFontSize(8.5);
            d.setTextColor(...COLORS.text);
            let xx = startX;
            for (let i = 0; i < row.length; i++) {
                const text = String(row[i] ?? '');
                const lines = d.splitTextToSize(text, widths[i] - 6);
                d.text(lines[0] || '', xx + 4, this.y + 12);
                xx += widths[i];
            }
            d.line(startX, this.y + rowH, startX + CONTENT.w, this.y + rowH);
            this.y += rowH;
        }
        this.y += 4;
    }

    bulletList(items) {
        const d = this.doc;
        for (const it of items) {
            this.ensure(14);
            d.setFont('helvetica', 'normal'); d.setFontSize(9);
            d.setTextColor(...COLORS.text);
            const lines = d.splitTextToSize('• ' + String(it), CONTENT.w - 12);
            d.text(lines, CONTENT.x + 6, this.y + 10);
            this.y += lines.length * 12 + 2;
        }
        this.y += 4;
    }

    render(results) {
        this.results = results;
        this.coverPage();
        this.summaryPage();
        this.findingsSection();
        this.binaryPage();
        this.entitlementsPage();
        this.atsPage();
        this.trackersPage();
        this.drawFooter();
        return this.doc;
    }

    save(filename) {
        this.doc.save(filename);
    }
}

function fmtSize(n) {
    if (n == null) return '?';
    const u = ['B','KB','MB','GB'];
    let i = 0;
    let v = Number(n);
    while (v >= 1024 && i < u.length - 1) { v /= 1024; i++; }
    return v.toFixed(v < 10 && i > 0 ? 2 : 1) + ' ' + u[i];
}

function tryParseXMLPlist(xml) {
    if (!xml || typeof DOMParser === 'undefined') return null;
    try {
        const doc = new DOMParser().parseFromString(xml, 'text/xml');
        const dict = doc.querySelector('plist > dict');
        if (!dict) return null;
        return walkPlist(dict);
    } catch (_) { return null; }
}
function walkPlist(node) {
    if (!node) return null;
    switch (node.tagName) {
        case 'string':  return node.textContent;
        case 'integer': return parseInt(node.textContent, 10);
        case 'real':    return parseFloat(node.textContent);
        case 'true':    return true;
        case 'false':   return false;
        case 'array':   return Array.from(node.children).map(walkPlist);
        case 'dict': {
            const o = {};
            const ch = Array.from(node.children);
            for (let i = 0; i < ch.length; i += 2) {
                if (ch[i].tagName === 'key') o[ch[i].textContent] = walkPlist(ch[i + 1]);
            }
            return o;
        }
        default: return node.textContent;
    }
}

function exportPDF(results, filenameBase) {
    const pdf = new PDF();
    pdf.render(results);
    const base = filenameBase || (results.appInfo?.appName || 'ipa') + '_' + (results.appInfo?.version || '');
    const safeBase = base.replace(/[^a-zA-Z0-9._-]/g, '_');
    pdf.save(safeBase + '_audit.pdf');
}

const api = { exportPDF, PDF };
if (typeof module !== 'undefined' && module.exports) module.exports = api;
else { root.IPAA = root.IPAA || {}; root.IPAA.PDF = api; }

})(typeof self !== 'undefined' ? self : this);
